services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    privileged: true
    ports:
      - "8080:8080"
      - "50000:50000"
      - "2443:2443"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./romulus:/var/jenkins_home/workspace/romulus
      - ./tests:/var/jenkins_home/workspace/tests
      - ./chromedriver:/var/jenkins_home/workspace/chromedriver
      - ./scripts:/var/jenkins_home/workspace/scripts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    command: >
      bash -c "
        apt-get update && 
        apt-get install -y python3 python3-pip python3-venv python3-full curl wget git openssh-client qemu-system-arm &&
        chmod -R +x /var/jenkins_home/workspace/scripts &&
        chmod -R +x /var/jenkins_home/workspace/chromedriver &&
        python3 -m venv /opt/venv &&
        . /opt/venv/bin/activate &&
        pip install selenium pytest requests locust webdriver-manager pytest-html &&
        /usr/local/bin/jenkins.sh
      "

  dind:
    image: docker:dind
    container_name: dind
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: ""

volumes:
  jenkins_home:
